language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jhpo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jhpo/react-test npm test

after_success:
    # Build images
    - docker build -t jhpo/multi-client ./client
    - docker build -t jhpo/multi-nginx ./nginx
    - docker build -t jhpo/multi-server ./server
    - docker build -t jhpo/multi-worker ./worker
    # Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
    # Push images to Docker Hub
    - docker push jhpo/multi-client
    - docker push jhpo/multi-nginx 
    - docker push jhpo/multi-server
    - docker push jhpo/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-2-368891396010'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
